export const Languages = [
{ name: "Arabic", value: "AR" },
{ name: "Bengali", value: "BN" },
{ name: "Bulgarian", value: "BG"},
{ name: "Chinese", value: "ZH" },
{ name: "Croatian", value: "HR"},
{ name: "Czech", value: "CS" },
{ name: "Danish", value: "DA" },
{ name: "Dutch", value: "NL" },
{ name: "English", value: "EN" },
{ name: "Estonia", value: "ET" },
{ name: "Finnish", value: "FI" },
{ name: "French", value: "FR" },
{ name: "German", value: "DE" },
{ name: "Greek", value: "EL" },
{ name: "Hebrew", value: "IW" },
{ name: "Hindi", value: "HI" },
{ name: "Hungarian", value: "HU" },
{ name: "Indonesian", value: "ID" },
{ name: "Italian", value: "IT" },
{ name: "Japanese", value: "JA" },
{ name: "Korean", value: "KO" },
{ name: "Latvian", value: "LV" },
{ name: "Norwegian", value: "NO" },
{ name: "Polish", value: "PL" },
{ name: "Portuguese", value: "PT" },
{ name: "Romanian", value: "RO" },
{ name: "Russian", value: "RU" },
{ name: "Serbian", value: "SR" },
{ name: "Slovak", value: "SK" },
{ name: "Slovenian", value: "SL" },
{ name: "Spanish", value: "ES" },
{ name: "Swahili", value: "SW" },
{ name: "Swedish", value: "SV" },
{ name: "Thai", value: "TH" },
{ name: "Turkish", value: "TR" },
{ name: "Ukrainian", value: "UK" },
{ name: "Vietnamese", value: "VI" }
]